### ISSUE TITLE
dtoverlayの追記内容について

### ISSUE THREAD

**Issue by rkarsnk** [masawada/bt2usbhid#1]
README.mdには，以下のように書いてありますが．
```
$ echo 'dtoverlay=dwc2' | sudo tee -a /boot/config.txt
```
USB HIDとして利用する場合，以下のように`g_hid`を追加しなくても動作するんでしょうか?
```
dtoverlay=dwc2,g_hid
```

**Comment by masawada** [comment]
@rkarsnk こんにちは、Issueを作成いただきありがとうございます。

前提として、このREADMEはRaspberry Piで動かすことを念頭に記しております。これはRaspberry Pi以外でGadget APIが動くハードウェアを私が所持していないためです。

dtoverlayはDevice Tree Overlayを読み込むための設定です。Raspberry Piにおいては [こちら](https://github.com/raspberrypi/firmware/tree/5325b7802ca90ac5c87440e6acbc37c96f08b054/boot/overlays) に指定可能な値がリストされており、g_hidは存在しません。そのため、Raspberry Piで動かす場合はむしろ指定するとうまく動かないのではと思います(古いOSではg_hidを指定する必要があったという話をインターネットで見かけました)。

もしRaspberry Piで古いOSをご利用でしたら最新のRaspberry Pi OSに更新することをおすすめします。Raspberry Pi以外のハードウェアを利用している場合などでg_hidを指定しないと動かないケースがあるようでしたら調査しますので、利用しているハードウェアの名称とOSのバージョン等をお知らせいただければと思います。

**Comment by rkarsnk** [comment]
@masawada こんにちは．

Raspberry Pi Zero W2 で使用しています．
導入しているOSは
- Raspberry Pi OS (bullseye) 
  - Linux raspberrypi 5.15.84-v8+ 
  - aarch64

で，最新のものを利用しています．

インターネット上に，g_hidをつける説明を書いた記事があったので，issueを作成しました．
最新のdtoverlayでは，g_hid不要の旨，こちらでも確認しました．情報ありがとうございます．

**Comment by masawada** [comment]
@rkarsnk ご連絡ありがとうございます。状況理解しました。
もしまた何かあればお気軽にお声がけください!
